# Introduction {#sec-intro}


This is where you introduce the main ideas of your thesis, and an overview of the context and background.

In a PhD, Chapter 2 would normally contain a literature review. Typically, Chapters 3--5 would contain your own contributions. Think of each of these as potential papers to be submitted to journals. Finally, Chapter 6 provides some concluding remarks, discussion, ideas for future research, and so on. Appendixes can contain additional material that don't fit into any chapters, but that you want to put on record. For example, additional tables, output, etc.

Again, notice the use of labels and references to automatically generate table numbers.



We present CONTRIBUTE, a pedagogical framework for capstone projects in which students contribute to an existing open source project. 
The framework was developed across four undergraduate cohorts through iterative cycles of classroom implementation, student feedback, and instructor reflection.
Conceptually, it builds on constructivist learning theory as a sensitizing perspective and extends it in several instructional building blocks, specifying practices for collaborating, organizing, navigating, training, regulating, implementing, branching, updating, testing, and evaluating.
CONTRIBUTE thereby organizes best practices from the classroom into a coherent, mid-range framework, designed to generalize across projects.
It offers instructors a pragmatic pathway to integrate programming, teamwork, and real-world open source software contribution, while integrating the software development work of students in an existing open source project.
We thereby support efforts to teach open source software development as an essential skill and contribute to initial efforts to incorporate open source principles and practical software development in the Information Systems curriculum.

